apiVersion: v1
kind: Service
metadata:
  name: nawatech-chatbot-service
  namespace: default
  labels:
    app: nawatech-chatbot
    component: backend
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8501
    protocol: TCP
    name: http
  selector:
    app: nawatech-chatbot

---
apiVersion: v1
kind: Service
metadata:
  name: nawatech-chatbot-nodeport
  namespace: default
  labels:
    app: nawatech-chatbot
    component: backend
    service-type: nodeport
spec:
  type: NodePort
  ports:
  - port: 8501
    targetPort: 8501
    nodePort: 30851
    protocol: TCP
    name: http
  selector:
    app: nawatech-chatbot

---
# Headless service for StatefulSet (if needed for scaling)
apiVersion: v1
kind: Service
metadata:
  name: nawatech-chatbot-headless
  namespace: default
  labels:
    app: nawatech-chatbot
    component: backend
    service-type: headless
spec:
  clusterIP: None
  ports:
  - port: 8501
    targetPort: 8501
    protocol: TCP
    name: http
  selector:
    app: nawatech-chatbot

---
# Ingress for external access
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nawatech-chatbot-ingress
  namespace: default
  labels:
    app: nawatech-chatbot
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - chatbot.nawatech.com
    secretName: nawatech-chatbot-tls
  rules:
  - host: chatbot.nawatech.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nawatech-chatbot-service
            port:
              number: 80

---
# Network Policy for security
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: nawatech-chatbot-netpol
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: nawatech-chatbot
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    - namespaceSelector:
        matchLabels:
          name: monitoring
    ports:
    - protocol: TCP
      port: 8501
  egress:
  - to: []
    ports:
    - protocol: TCP
      port: 443  # HTTPS for OpenAI API
    - protocol: TCP
      port: 53   # DNS
    - protocol: UDP
      port: 53   # DNS